import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

import "./globals.css";

import { ThemeProvider } from '@mui/material/styles';
import theme from './theme';

import TopBar from '../components/TopBar';


export const metadata: Metadata = {
  title: "Group Ordering App",
  description: "Order a meal for you and your friends or coworkers.",
};

export default function RootLayout(props) {
  return (
    <html lang="en" >
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <TopBar />
            {props.children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}

/*import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}*/
